In [1]:
import numpy as np 
from sklearn import datasets as ds

In [2]:
iris = ds.load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
X  = iris['data'][:,3:4]
y = (iris['target'] == 2).astype(np.int8)

In [4]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X, y)

LogisticRegression()

In [5]:
log_reg.intercept_

array([-7.1947083])

In [6]:
log_reg.coef_

array([[4.3330846]])

In [7]:
X_new = np.linspace(0, 3, 1000).reshape(1000, 1)
y_proba = log_reg.predict_proba(X_new)[:,1:]
y_pred = log_reg.predict(X_new)
y_proba 

array([[7.49984089e-04],
       [7.59799387e-04],
       [7.69743043e-04],
       [7.79816732e-04],
       [7.90022153e-04],
       [8.00361024e-04],
       [8.10835088e-04],
       [8.21446109e-04],
       [8.32195877e-04],
       [8.43086202e-04],
       [8.54118919e-04],
       [8.65295886e-04],
       [8.76618985e-04],
       [8.88090125e-04],
       [8.99711238e-04],
       [9.11484280e-04],
       [9.23411234e-04],
       [9.35494108e-04],
       [9.47734937e-04],
       [9.60135782e-04],
       [9.72698731e-04],
       [9.85425898e-04],
       [9.98319426e-04],
       [1.01138149e-03],
       [1.02461427e-03],
       [1.03802002e-03],
       [1.05160097e-03],
       [1.06535943e-03],
       [1.07929769e-03],
       [1.09341812e-03],
       [1.10772307e-03],
       [1.12221497e-03],
       [1.13689623e-03],
       [1.15176935e-03],
       [1.16683681e-03],
       [1.18210115e-03],
       [1.19756493e-03],
       [1.21323076e-03],
       [1.22910127e-03],
       [1.24517913e-03],


In [8]:
from matplotlib import pyplot as plt
%matplotlib 
plt.scatter(X_new, y_pred, color = "red")
plt.plot(X_new, y_proba, color = "blue")


Using matplotlib backend: <object object at 0x000001E785D01D20>
